language: node_js
node_js:
  - "8.10"

addons:
  apt:
    packages:
    - lftp
    
before_install:
  - npm install -g hexo

install:
  - npm install

script:
  - hexo generate
  #- hexo deploy --host=$FTP_SERVER --port=22 --user=$FTP_USER --pass=$FTP_PASSWORD --verbose=true --remotePath=www
#   - apt-get update
#   - apt-get install -y lftp
  - lftp -e "set ftp:ssl-allow no; mirror -R public www ; quit" -u $FTP_USER,$FTP_PASSWORD $FTP_SERVER
