language: node_js
node_js:
  - "8.10"

before_install:
  - npm install -g hexo

install:
  - npm install

script:
  - hexo generate

after_success:
  gulp deploy --user $FTP_USER --password $FTP_PASSWORD --server $FTP_SERVER
